INSERT INTO users (name, email, password) 
VALUES (Tommy Wiseau, tw@theroom.com, $2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.)
INSERT INTO users (name, email, password) 
VALUES (Keanu Reeves, kr@matrix.com, $2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.)
INSERT INTO users (name, email, password) 
VALUES (Justin Bieber, jb@beibs.com, $2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.)
INSERT INTO users (name, email, password) 
VALUES (Jim Carrey, jc@carrey.com, $2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.)

INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, city, province, post_code, active)
